# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7b1c4d49a8774fc82870fb6d6924e72509b141b16b365f1b3227c1485601ed19a95f91c9a71aecb82d54cb06a6b943bdccee1f29c4e34f8f4019bcfec41b5ce

test:
  secret_key_base: eb1923b052e37077fde7efe06c596b4bf8c16c66f66cfecb324e0dda22be24febf19fa2371785b9c4b6c865a6e1ed9e5f0120300a61a8a2fb15b783604a73a7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
